/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/photonic_convergence.glb 
Author: Tycho Magnetic Anomaly (https://sketchfab.com/Tycho_Magnetic_Anomaly)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/photonic-convergence-ad8c133676824aa99a4c18626e8787f7
Title: Photonic Convergence
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

const Photonic = (props) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/photonic_convergence.glb')
  const { actions,names } = useAnimations(animations, group)
  console.log(names);

  useEffect(()=>{
    actions[names[0]].reset().fadeIn(0.5).play();
  },[])


  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Cylinder_0" position={[0, -15.741, 0]} scale={0}>
                <mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder001_1" position={[1.018, 5.891, 14.562]} scale={0}>
                <mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder002_2" position={[-14.777, 4.054, 3.604]} scale={0}>
                <mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder003_3" position={[7.275, 11.132, -8.423]} scale={0}>
                <mesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder004_4" position={[-13.312, -1.989, 8.162]} scale={0}>
                <mesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder005_5" position={[-2.358, 8.25, -13.197]} scale={0}>
                <mesh name="Object_14" geometry={nodes.Object_14.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder006_6" position={[-0.542, -10.888, -11.356]} scale={0}>
                <mesh name="Object_16" geometry={nodes.Object_16.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder007_7" position={[14.787, 4.002, 3.623]} scale={0}>
                <mesh name="Object_18" geometry={nodes.Object_18.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder008_8" position={[-5.463, -9.072, 11.647]} scale={0}>
                <mesh name="Object_20" geometry={nodes.Object_20.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder009_9" position={[6.1, -8.527, -11.742]} scale={0}>
                <mesh name="Object_22" geometry={nodes.Object_22.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder010_10" position={[15.549, 0.692, 2.354]} scale={0}>
                <mesh name="Object_24" geometry={nodes.Object_24.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder011_11" position={[-5.356, 12.627, -7.723]} scale={0}>
                <mesh name="Object_26" geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder012_12" position={[13.719, -6.621, 3.967]} scale={0}>
                <mesh name="Object_28" geometry={nodes.Object_28.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder013_13" position={[0.442, 15.684, 1.273]} scale={0}>
                <mesh name="Object_30" geometry={nodes.Object_30.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder014_14" position={[8.665, -6.503, -11.42]} scale={0}>
                <mesh name="Object_32" geometry={nodes.Object_32.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder015_15" position={[-9.69, 11.094, -5.551]} scale={0}>
                <mesh name="Object_34" geometry={nodes.Object_34.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder016_16" position={[7.257, 13.555, 3.376]} scale={0}>
                <mesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder017_17" position={[-8.198, -5.504, 12.259]} scale={0}>
                <mesh name="Object_38" geometry={nodes.Object_38.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder018_18" position={[7.721, 13.026, -4.302]} scale={0}>
                <mesh name="Object_40" geometry={nodes.Object_40.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder019_19" position={[2.36, -3.51, 15.162]} scale={0}>
                <mesh name="Object_42" geometry={nodes.Object_42.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder020_20" position={[10.835, -11.415, -0.286]} scale={0}>
                <mesh name="Object_44" geometry={nodes.Object_44.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder021_21" position={[4.467, 7.246, -13.241]} scale={0}>
                <mesh name="Object_46" geometry={nodes.Object_46.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder022_22" position={[4.788, -14.99, 0.416]} scale={0}>
                <mesh name="Object_48" geometry={nodes.Object_48.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder023_23" position={[0.02, 3.744, 15.29]} scale={0}>
                <mesh name="Object_50" geometry={nodes.Object_50.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder024_24" position={[-8.025, -9.084, -10.043]} scale={0}>
                <mesh name="Object_52" geometry={nodes.Object_52.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder025_25" position={[-9.458, 7.007, 10.452]} scale={0}>
                <mesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder026_59" position={[0, -15.741, 0]} scale={0}>
                <mesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder027_60" position={[1.018, 5.891, 14.562]} scale={0}>
                <mesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder028_61" position={[-14.777, 4.054, 3.604]} scale={0}>
                <mesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder029_62" position={[7.275, 11.132, -8.423]} scale={0}>
                <mesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder030_63" position={[-13.312, -1.989, 8.162]} scale={0}>
                <mesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder031_64" position={[-2.358, 8.25, -13.197]} scale={0}>
                <mesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder032_65" position={[-0.542, -10.888, -11.356]} scale={0}>
                <mesh name="Object_68" geometry={nodes.Object_68.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder033_66" position={[14.787, 4.002, 3.623]} scale={0}>
                <mesh name="Object_70" geometry={nodes.Object_70.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder034_67" position={[-5.463, -9.072, 11.647]} scale={0}>
                <mesh name="Object_72" geometry={nodes.Object_72.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder035_68" position={[6.1, -8.527, -11.742]} scale={0}>
                <mesh name="Object_74" geometry={nodes.Object_74.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder036_69" position={[15.549, 0.692, 2.354]} scale={0}>
                <mesh name="Object_76" geometry={nodes.Object_76.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder037_70" position={[-5.356, 12.627, -7.723]} scale={0}>
                <mesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder038_71" position={[13.719, -6.621, 3.967]} scale={0}>
                <mesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder039_72" position={[0.442, 15.684, 1.273]} scale={0}>
                <mesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder040_73" position={[8.665, -6.503, -11.42]} scale={0}>
                <mesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder041_74" position={[-9.69, 11.094, -5.551]} scale={0}>
                <mesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder042_75" position={[7.257, 13.555, 3.376]} scale={0}>
                <mesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder043_76" position={[-8.198, -5.504, 12.259]} scale={0}>
                <mesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder044_77" position={[7.721, 13.026, -4.302]} scale={0}>
                <mesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder045_78" position={[2.36, -3.51, 15.162]} scale={0}>
                <mesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder046_79" position={[10.835, -11.415, -0.286]} scale={0}>
                <mesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder047_80" position={[4.467, 7.246, -13.241]} scale={0}>
                <mesh name="Object_98" geometry={nodes.Object_98.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder048_81" position={[4.788, -14.99, 0.416]} scale={0}>
                <mesh name="Object_100" geometry={nodes.Object_100.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder049_82" position={[0.02, 3.744, 15.29]} scale={0}>
                <mesh name="Object_102" geometry={nodes.Object_102.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder050_83" position={[-8.025, -9.084, -10.043]} scale={0}>
                <mesh name="Object_104" geometry={nodes.Object_104.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder051_84" position={[-9.458, 7.007, 10.452]} scale={0}>
                <mesh name="Object_106" geometry={nodes.Object_106.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder053_119" position={[0.024, 0.141, 0.349]} scale={0.606}>
                <mesh name="Object_110" geometry={nodes.Object_110.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder054_120" position={[-6.235, 1.71, 1.521]}>
                <mesh name="Object_112" geometry={nodes.Object_112.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder055_121" position={[6.624, 10.137, -7.67]} scale={0.352}>
                <mesh name="Object_114" geometry={nodes.Object_114.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder056_122" position={[-0.113, -0.017, 0.069]} scale={0}>
                <mesh name="Object_116" geometry={nodes.Object_116.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder057_123" position={[-0.41, 1.434, -2.294]}>
                <mesh name="Object_118" geometry={nodes.Object_118.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder058_124" position={[-0.375, -7.542, -7.866]} scale={0.972}>
                <mesh name="Object_120" geometry={nodes.Object_120.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder059_125" position={[14.787, 4.002, 3.623]} scale={0}>
                <mesh name="Object_122" geometry={nodes.Object_122.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder060_126" position={[-0.046, -0.077, 0.099]} scale={0.198}>
                <mesh name="Object_124" geometry={nodes.Object_124.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder061_127" position={[1.62, -2.264, -3.118]}>
                <mesh name="Object_126" geometry={nodes.Object_126.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder062_128" position={[12.291, 0.547, 1.861]} scale={0.784}>
                <mesh name="Object_128" geometry={nodes.Object_128.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder063_129" position={[-5.356, 12.627, -7.723]} scale={0}>
                <mesh name="Object_130" geometry={nodes.Object_130.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder064_130" position={[0.923, -0.446, 0.267]} scale={0.945}>
                <mesh name="Object_132" geometry={nodes.Object_132.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder065_131" position={[0.235, 8.34, 0.677]}>
                <mesh name="Object_134" geometry={nodes.Object_134.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder066_132" position={[0.073, -0.055, -0.097]} scale={0}>
                <mesh name="Object_136" geometry={nodes.Object_136.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder067_133" position={[-0.652, 0.747, -0.374]} scale={0.945}>
                <mesh name="Object_138" geometry={nodes.Object_138.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder068_134" position={[3.859, 7.208, 1.795]}>
                <mesh name="Object_140" geometry={nodes.Object_140.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder069_135" position={[-7.92, -5.317, 11.842]} scale={0.104}>
                <mesh name="Object_142" geometry={nodes.Object_142.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder070_136" position={[0.065, 0.11, -0.036]} scale={0.055}>
                <mesh name="Object_144" geometry={nodes.Object_144.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder071_137" position={[0.627, -0.932, 4.026]}>
                <mesh name="Object_146" geometry={nodes.Object_146.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder072_138" position={[8.565, -9.023, -0.226]} scale={0.784}>
                <mesh name="Object_148" geometry={nodes.Object_148.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder073_139" position={[0.107, 0.174, -0.318]} scale={0.606}>
                <mesh name="Object_150" geometry={nodes.Object_150.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder074_140" position={[1.763, -5.518, 0.153]}>
                <mesh name="Object_152" geometry={nodes.Object_152.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder075_141" position={[0.02, 3.744, 15.29]} scale={0}>
                <mesh name="Object_154" geometry={nodes.Object_154.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder076_142" position={[-1.072, -1.214, -1.342]}>
                <mesh name="Object_156" geometry={nodes.Object_156.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder077_143" position={[-6.057, 4.487, 6.693]}>
                <mesh name="Object_158" geometry={nodes.Object_158.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder078_179" position={[-5.634, -11.49, 9.167]} scale={0}>
                <mesh name="Object_164" geometry={nodes.Object_164.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder079_180" position={[4.672, -5.41, -14.025]} scale={0}>
                <mesh name="Object_166" geometry={nodes.Object_166.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder080_181" position={[15.651, -1.108, 1.27]} scale={0}>
                <mesh name="Object_168" geometry={nodes.Object_168.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder081_182" position={[-4.596, 14.612, -3.626]} scale={0}>
                <mesh name="Object_170" geometry={nodes.Object_170.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder082_183" position={[13.256, -8.431, 0.996]} scale={0}>
                <mesh name="Object_172" geometry={nodes.Object_172.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder083_184" position={[1.925, 14.662, 5.395]} scale={0}>
                <mesh name="Object_174" geometry={nodes.Object_174.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder084_185" position={[-6.124, -0.348, 14.497]} scale={0}>
                <mesh name="Object_176" geometry={nodes.Object_176.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder085_186" position={[-11.047, 2.115, -11.013]} scale={0}>
                <mesh name="Object_178" geometry={nodes.Object_178.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder086_187" position={[4.47, -15.082, -0.579]} scale={0}>
                <mesh name="Object_180" geometry={nodes.Object_180.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder087_188" position={[-11.367, 2.371, 10.629]} scale={0}>
                <mesh name="Object_182" geometry={nodes.Object_182.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder088_189" position={[-13.224, 0.639, -8.516]} scale={0}>
                <mesh name="Object_184" geometry={nodes.Object_184.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder089_190" position={[7.507, 13.833, 0.269]} scale={0}>
                <mesh name="Object_186" geometry={nodes.Object_186.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder090_191" position={[-13.804, -5.99, -4.622]} scale={0}>
                <mesh name="Object_188" geometry={nodes.Object_188.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder091_192" position={[5.519, 10.638, -10.206]} scale={0}>
                <mesh name="Object_190" geometry={nodes.Object_190.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder092_193" position={[-12.88, 3.915, 8.158]} scale={0}>
                <mesh name="Object_192" geometry={nodes.Object_192.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder093_194" position={[11.39, 10.769, 1.448]} scale={0}>
                <mesh name="Object_194" geometry={nodes.Object_194.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder094_195" position={[-0.892, 8.421, -13.27]} scale={0}>
                <mesh name="Object_196" geometry={nodes.Object_196.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder095_196" position={[8.362, -13.194, -1.946]} scale={0}>
                <mesh name="Object_198" geometry={nodes.Object_198.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder096_197" position={[-3.335, 13.264, -7.793]} scale={0}>
                <mesh name="Object_200" geometry={nodes.Object_200.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder097_198" position={[0.24, -12.528, -9.528]} scale={0}>
                <mesh name="Object_202" geometry={nodes.Object_202.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder098_199" position={[-13.934, -6.94, 2.339]} scale={0}>
                <mesh name="Object_204" geometry={nodes.Object_204.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder099_200" position={[-4.606, 14.715, 3.171]} scale={0}>
                <mesh name="Object_206" geometry={nodes.Object_206.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder100_201" position={[-9.588, -10.692, 6.447]} scale={0}>
                <mesh name="Object_208" geometry={nodes.Object_208.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder101_202" position={[4.979, -7.578, -12.868]} scale={0}>
                <mesh name="Object_210" geometry={nodes.Object_210.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder102_203" position={[1.59, -0.745, 15.643]} scale={0}>
                <mesh name="Object_212" geometry={nodes.Object_212.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder103_204" position={[13.545, -2.982, -7.446]} scale={0}>
                <mesh name="Object_214" geometry={nodes.Object_214.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder104_238" position={[-5.634, -11.49, 9.167]} scale={0}>
                <mesh name="Object_216" geometry={nodes.Object_216.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder105_239" position={[4.672, -5.41, -14.025]} scale={0}>
                <mesh name="Object_218" geometry={nodes.Object_218.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder106_240" position={[15.651, -1.108, 1.27]} scale={0}>
                <mesh name="Object_220" geometry={nodes.Object_220.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder107_241" position={[-4.596, 14.612, -3.626]} scale={0}>
                <mesh name="Object_222" geometry={nodes.Object_222.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder108_242" position={[13.256, -8.431, 0.996]} scale={0}>
                <mesh name="Object_224" geometry={nodes.Object_224.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder109_243" position={[1.925, 14.662, 5.395]} scale={0}>
                <mesh name="Object_226" geometry={nodes.Object_226.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder110_244" position={[-6.124, -0.348, 14.497]} scale={0}>
                <mesh name="Object_228" geometry={nodes.Object_228.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder111_245" position={[-11.047, 2.115, -11.013]} scale={0}>
                <mesh name="Object_230" geometry={nodes.Object_230.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder112_246" position={[4.47, -15.082, -0.579]} scale={0}>
                <mesh name="Object_232" geometry={nodes.Object_232.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder113_247" position={[-11.367, 2.371, 10.629]} scale={0}>
                <mesh name="Object_234" geometry={nodes.Object_234.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder114_248" position={[-13.224, 0.639, -8.516]} scale={0}>
                <mesh name="Object_236" geometry={nodes.Object_236.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder115_249" position={[7.507, 13.833, 0.269]} scale={0}>
                <mesh name="Object_238" geometry={nodes.Object_238.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder116_250" position={[-13.804, -5.99, -4.622]} scale={0}>
                <mesh name="Object_240" geometry={nodes.Object_240.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder117_251" position={[5.519, 10.638, -10.206]} scale={0}>
                <mesh name="Object_242" geometry={nodes.Object_242.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder118_252" position={[-12.88, 3.915, 8.158]} scale={0}>
                <mesh name="Object_244" geometry={nodes.Object_244.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder119_253" position={[11.39, 10.769, 1.448]} scale={0}>
                <mesh name="Object_246" geometry={nodes.Object_246.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder120_254" position={[-0.892, 8.421, -13.27]} scale={0}>
                <mesh name="Object_248" geometry={nodes.Object_248.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder121_255" position={[8.362, -13.194, -1.946]} scale={0}>
                <mesh name="Object_250" geometry={nodes.Object_250.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder122_256" position={[-3.335, 13.264, -7.793]} scale={0}>
                <mesh name="Object_252" geometry={nodes.Object_252.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder123_257" position={[0.24, -12.528, -9.528]} scale={0}>
                <mesh name="Object_254" geometry={nodes.Object_254.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder124_258" position={[-13.934, -6.94, 2.339]} scale={0}>
                <mesh name="Object_256" geometry={nodes.Object_256.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder125_259" position={[-4.606, 14.715, 3.171]} scale={0}>
                <mesh name="Object_258" geometry={nodes.Object_258.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder126_260" position={[-9.588, -10.692, 6.447]} scale={0}>
                <mesh name="Object_260" geometry={nodes.Object_260.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder127_261" position={[4.979, -7.578, -12.868]} scale={0}>
                <mesh name="Object_262" geometry={nodes.Object_262.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder128_262" position={[1.59, -0.745, 15.643]} scale={0}>
                <mesh name="Object_264" geometry={nodes.Object_264.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder129_263" position={[13.545, -2.982, -7.446]} scale={0}>
                <mesh name="Object_266" geometry={nodes.Object_266.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder130_297" position={[-0.048, -0.097, 0.078]} scale={0}>
                <mesh name="Object_268" geometry={nodes.Object_268.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder131_298" position={[0.112, -0.13, -0.336]} scale={0.606}>
                <mesh name="Object_270" geometry={nodes.Object_270.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder132_299" position={[6.604, -0.468, 0.536]}>
                <mesh name="Object_272" geometry={nodes.Object_272.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder133_300" position={[-4.185, 13.306, -3.302]} scale={0.352}>
                <mesh name="Object_274" geometry={nodes.Object_274.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder134_301" position={[0.112, -0.071, 0.008]} scale={0}>
                <mesh name="Object_276" geometry={nodes.Object_276.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder135_302" position={[0.335, 2.549, 0.938]}>
                <mesh name="Object_278" geometry={nodes.Object_278.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder136_303" position={[-4.242, -0.241, 10.042]} scale={0.972}>
                <mesh name="Object_280" geometry={nodes.Object_280.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder137_304" position={[-11.047, 2.115, -11.013]} scale={0}>
                <mesh name="Object_282" geometry={nodes.Object_282.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder138_305" position={[0.038, -0.128, -0.005]} scale={0.198}>
                <mesh name="Object_284" geometry={nodes.Object_284.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder139_306" position={[-3.018, 0.63, 2.822]}>
                <mesh name="Object_286" geometry={nodes.Object_286.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder140_307" position={[-10.453, 0.505, -6.731]} scale={0.784}>
                <mesh name="Object_288" geometry={nodes.Object_288.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder141_308" position={[7.507, 13.833, 0.269]} scale={0}>
                <mesh name="Object_290" geometry={nodes.Object_290.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder142_309" position={[-0.929, -0.403, -0.311]} scale={0.945}>
                <mesh name="Object_292" geometry={nodes.Object_292.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder143_310" position={[2.935, 5.657, -5.427]}>
                <mesh name="Object_294" geometry={nodes.Object_294.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder144_311" position={[-0.109, 0.033, 0.069]} scale={0}>
                <mesh name="Object_296" geometry={nodes.Object_296.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder145_312" position={[0.767, 0.725, 0.097]} scale={0.945}>
                <mesh name="Object_298" geometry={nodes.Object_298.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder146_313" position={[-0.474, 4.478, -7.057]}>
                <mesh name="Object_300" geometry={nodes.Object_300.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder147_314" position={[8.078, -12.745, -1.88]} scale={0.104}>
                <mesh name="Object_302" geometry={nodes.Object_302.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder148_315" position={[-0.028, 0.112, -0.066]} scale={0.055}>
                <mesh name="Object_304" geometry={nodes.Object_304.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder149_316" position={[0.064, -3.327, -2.53]}>
                <mesh name="Object_306" geometry={nodes.Object_306.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder150_317" position={[-11.014, -5.485, 1.849]} scale={0.784}>
                <mesh name="Object_308" geometry={nodes.Object_308.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder151_318" position={[-0.11, 0.353, 0.076]} scale={0.606}>
                <mesh name="Object_310" geometry={nodes.Object_310.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder152_319" position={[-3.529, -3.936, 2.373]}>
                <mesh name="Object_312" geometry={nodes.Object_312.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder153_320" position={[4.979, -7.578, -12.868]} scale={0}>
                <mesh name="Object_314" geometry={nodes.Object_314.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder154_321" position={[0.212, -0.1, 2.09]}>
                <mesh name="Object_316" geometry={nodes.Object_316.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder155_322" position={[8.674, -1.91, -4.768]}>
                <mesh name="Object_318" geometry={nodes.Object_318.geometry} material={materials['Material.001']} />
              </group>
              <group name="Cylinder052_118" position={[0, -0.133, 0]} scale={0}>
                <mesh name="Object_108" geometry={nodes.Object_108.geometry} material={materials['Material.001']} />
              </group>
              <group name="Sphere_177" scale={16.172}>
                <mesh name="Object_160" geometry={nodes.Object_160.geometry} material={materials['Material.002']} />
              </group>
              <group name="Sphere001_178" scale={16.436}>
                <mesh name="Object_162" geometry={nodes.Object_162.geometry} material={materials['Material.004']} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Photonic

useGLTF.preload('/models/photonic_convergence.glb')
